version: '3.8'

services:
  ai_agent:
    build: .
    container_name: devops_ai_agent
    ports:
      - "8000:8000"
    environment:
     - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped